environment.name = VoltMX Technohub
mf.appname = StandardBank
mf.app.version = 1.0
mf.runtime.app.version = 1.0
account.id = 100000032
cloud.environment = undefined
mobilefabric.url = https://manage.hclvoltmx.com
cloud.username = undefined
cloud.password = undefined
mode = 2
project.name = undefined
version = 1.0.0
appid = StandardBank
publish.web = undefined
publish.service = undefined
mfa.secret.key = undefined
fabric.token = eyAidHlwIjogImp3dCIsICJhbGciOiAiUlMyNTYiIH0.eyAiX2JlYXJlcl90b2tlbiI6ICJiYzQyOTkzMjAyMGVlODI3YmQwMTQ4MTBlYTkzZmM5NzI2OWE3ODhhYThlMjYzMTdiOTY4MjdjYzdiMjFlODFhODk4ZjMyNWY2MWY3M2IxOSIsICJfZW1haWwiOiAiYmhhcmdhdmkuc2lyeWFwcmVkZHlAaGNsLmNvbSIsICJfdmVyIjogInYyLjAiLCAiaXNzIjogImh0dHBzOi8vYWNjb3VudHMuYXV0aC5oY2x2b2x0bXgubmV0IiwgIl9zY29wZSI6ICJnIiwgIl9pc3NtZXRhIjogIi9tZXRhZGF0YS85bDR2QVhkVV9WTnR0d1JNQnBsRF9nPT0iLCAiX3Nlc3Npb25faWQiOiAiNDUwMzNjYzMtMWI4My00NWEzLWI5ZTEtMTEyZDNlNzJjM2FhIiwgIl9wdWlkIjogNDkzMTc5MzgzOTE3NiwgIl9pZHAiOiAia29ueV9hY2NvdW50cyIsICJleHAiOiAxNzc1ODM4NTIxLCAiaWF0IjogMTc3NTgzNDkyMSwgIl9zZXNzaW9uX3RpZCI6ICJhY2NvdW50cyIsICJfcHJvdl91c2VyaWQiOiAiMzQ3OThhNzUtZmE0ZC00ZWU0LWEzOTktZmVkNTM2MzNhZDRlIiwgImp0aSI6ICIyNmNiYWFjZS0xNzgyLTQ4MmItYTZiNi03MWNlZWM3ZDJkOTQiLCAiX2FjcyI6ICJhY2NvdW50cyIgfQ.ERLDiQKGYVl20Yx4kcWY9ZORtvuMUpIK6mVP4FNvZtW_U9lFZTICzfMW_4vhchtxP4OKO7e9i9UW7-UvsBQCZEaTQpyWPkdLxbFFyx50lskcns372_Z3LPifsbYCVlhvvIuJJJSNVKptQVcY5x6o48WzOIDPwobzOjr61Sf_1vKDrgP-2weB1eNX6SXV3j4RK7LNtSIR1OIEKGpj02rqeyZqNFZYukwmoYqPjH8JpK0547wjWQ7971qBFToZymLT0XVtG9R9rvdnIe7nmJWrwIK-qX0uB57OMSwIhREiVJIlDvziw00bo4hC1KSLPgDtxVeajWjUFZLatMlexer7ug
javaloc = /Applications/Volt Iris/jre/Contents/Home
