environment.name = VoltMX Technohub
mf.appname = StandardBank
mf.app.version = 1.0
mf.runtime.app.version = 1.0
account.id = 100000032
cloud.environment = undefined
mobilefabric.url = https://manage.hclvoltmx.com
cloud.username = undefined
cloud.password = undefined
mode = 2
project.name = undefined
version = 1.0.0
appid = StandardBank
publish.web = undefined
publish.service = undefined
mfa.secret.key = undefined
fabric.token = eyAidHlwIjogImp3dCIsICJhbGciOiAiUlMyNTYiIH0.eyAiX2JlYXJlcl90b2tlbiI6ICI4NGM5NTljMmI1ZDBjNjU3ZmQ4YjgyNTMxMWUxZGY4MWQyMDZjM2Y0NDk0ODc0YTM1ZWFlZTk5ZmE3NDg5YjUyMjA2MjhlYzkwYzc0YmY5ZSIsICJfZW1haWwiOiAiYmhhcmdhdmkuc2lyeWFwcmVkZHlAaGNsLmNvbSIsICJfdmVyIjogInYyLjAiLCAiaXNzIjogImh0dHBzOi8vYWNjb3VudHMuYXV0aC5oY2x2b2x0bXgubmV0IiwgIl9zY29wZSI6ICJnIiwgIl9pc3NtZXRhIjogIi9tZXRhZGF0YS85bDR2QVhkVV9WTnR0d1JNQnBsRF9nPT0iLCAiX3Nlc3Npb25faWQiOiAiYzRmMWJlNTYtZjM0Zi00MzllLWI5NTgtYjI2YzlkNmU3NzM2IiwgIl9wdWlkIjogNDkzMTc5MzgzOTE3NiwgIl9pZHAiOiAia29ueV9hY2NvdW50cyIsICJleHAiOiAxNzgxMTY4MTM5LCAiaWF0IjogMTc4MTE2NDUzOSwgIl9zZXNzaW9uX3RpZCI6ICJhY2NvdW50cyIsICJfcHJvdl91c2VyaWQiOiAiMzQ3OThhNzUtZmE0ZC00ZWU0LWEzOTktZmVkNTM2MzNhZDRlIiwgImp0aSI6ICJhMDJlNjMxOS1mMTJhLTRjNjQtOTJmOC1jZWM5NTI1ODEzM2YiLCAiX2FjcyI6ICJhY2NvdW50cyIgfQ.fs33ufF30jgV4mWZrzL0q0EMgnGCrZ5X07ORaBZ2divkIwzUfXAMApSVqJjLNWP6w2HzpQ4yHqBp6wf75J5gpzZUUFK72Q7e8U1RERco1LK-fiTvVwOp9oACylz88ZjWyW02kks_yZel4vArn137VWE0i7DBR0XAvXdclKwfO5yBnoMaPGPP0S7WCOkhde6FVqC2RWV_qdNREEK4jBliWH-aXetKkUjVhhrCiWkocYDrcKuAXUHf1CWNU2KY79S1Ka1hmPdPhfXeaH40GDEFsGLC8F03yhfZuGQ1tD9eQ_Qjpuu3GBn8PRgkaShphwuQOQfySjvDjZxADFQ5s2c-Tw
javaloc = /Applications/Volt Iris/jre/Contents/Home
