environment.name = VoltMX Technohub
mf.appname = StandardBank
mf.app.version = 1.0
mf.runtime.app.version = 1.0
account.id = 100000032
cloud.environment = undefined
mobilefabric.url = https://manage.hclvoltmx.com
cloud.username = undefined
cloud.password = undefined
mode = 2
project.name = undefined
version = 1.0.0
appid = StandardBank
publish.web = undefined
publish.service = undefined
mfa.secret.key = undefined
fabric.token = eyAidHlwIjogImp3dCIsICJhbGciOiAiUlMyNTYiIH0.eyAiX2JlYXJlcl90b2tlbiI6ICJjMWNhNjVmMTk4OGY3MmZlMDdjZjJmMGRlOGM0OGIwZTZhYTU5YzI3MzIxNzFkMTVhODczYjYxNzk5OGMyY2I0MDJlOGIwNWZhYmZmY2JlMiIsICJfZW1haWwiOiAiYmhhcmdhdmkuc2lyeWFwcmVkZHlAaGNsLmNvbSIsICJfdmVyIjogInYyLjAiLCAiaXNzIjogImh0dHBzOi8vYWNjb3VudHMuYXV0aC5oY2x2b2x0bXgubmV0IiwgIl9zY29wZSI6ICJnIiwgIl9pc3NtZXRhIjogIi9tZXRhZGF0YS85bDR2QVhkVV9WTnR0d1JNQnBsRF9nPT0iLCAiX3Nlc3Npb25faWQiOiAiNzdlYTA0MjEtZDAxYS00MTAyLWI4Y2MtNWUyMjM1YWUzNzZmIiwgIl9wdWlkIjogNDkzMTc5MzgzOTE3NiwgIl9pZHAiOiAia29ueV9hY2NvdW50cyIsICJleHAiOiAxNzgyODIwMzAzLCAiaWF0IjogMTc4MjgxNjcwMywgIl9zZXNzaW9uX3RpZCI6ICJhY2NvdW50cyIsICJfcHJvdl91c2VyaWQiOiAiMzQ3OThhNzUtZmE0ZC00ZWU0LWEzOTktZmVkNTM2MzNhZDRlIiwgImp0aSI6ICJhMTRjYTU2OS1mYTJmLTRjMzMtOTJhNS1jNzczNGI1NjkzY2UiLCAiX2FjcyI6ICJhY2NvdW50cyIgfQ.dE069u1Cql5ACyaxVmxrhZpzFBh-YWm0DLRjjucJnY5_BnEZWGRg-PWrCB5V5pSnUvDBnK-iWzAWSv-W25mmVdcSoTN0Nq5SQQ-wNQBjG34nQ6PJHkZjqrvFKFGPXv0aD2_LXstlYP_EmLl2yC1Fl1bZY87WfMQmUhjsmfcyRQSGlMsKAWMVGGT8vHqm1s5A2f4gds3TTT0qH8NE6vY_j6n_kbZ34s2FLvAb2I4XYLJdlfFJPuIt9mdDXg98e4RLUXoxIhXHPNb61lnfUicQdgPfmAWZ9hkCJBx7AHCP0scR8Pg1zMM6Dj1cQhnYtY7uUOm-4dPzYZeLwDrNgTTtwQ
javaloc = /Applications/Volt Iris/jre/Contents/Home
