environment.name = VoltMX Technohub
mf.appname = SuspendList
mf.app.version = 1.0
mf.runtime.app.version = 1.0
account.id = 100000032
cloud.environment = undefined
mobilefabric.url = https://manage.hclvoltmx.com
cloud.username = undefined
cloud.password = undefined
mode = 2
project.name = undefined
version = 1.0.0
appid = SuspendList
publish.web = undefined
publish.service = undefined
mfa.secret.key = undefined
fabric.token = eyAidHlwIjogImp3dCIsICJhbGciOiAiUlMyNTYiIH0.eyAiX2JlYXJlcl90b2tlbiI6ICI0Y2ViMTViOTU5ZTMwMzdiNDIzOWNlMTE2ZWNjMDQwY2RlZTU3MmUxYmFkMjg1NmRjNTA2NDg4ZGJhZGYxYmNiNjE1MDE4MTllZjQ5MzhjMSIsICJfZW1haWwiOiAiYmhhcmdhdmkuc2lyeWFwcmVkZHlAaGNsLmNvbSIsICJfdmVyIjogInYyLjAiLCAiaXNzIjogImh0dHBzOi8vYWNjb3VudHMuYXV0aC5oY2x2b2x0bXgubmV0IiwgIl9zY29wZSI6ICJnIiwgIl9pc3NtZXRhIjogIi9tZXRhZGF0YS85bDR2QVhkVV9WTnR0d1JNQnBsRF9nPT0iLCAiX3Nlc3Npb25faWQiOiAiNGQyMzBhODYtNDkyZS00OGU5LWEwYzYtNzg3YzYwZGJlY2U3IiwgIl9wdWlkIjogNDkzMTc5MzgzOTE3NiwgIl9pZHAiOiAia29ueV9hY2NvdW50cyIsICJleHAiOiAxNzczODUxMTE4LCAiaWF0IjogMTc3Mzg0NzUxOCwgIl9zZXNzaW9uX3RpZCI6ICJhY2NvdW50cyIsICJfcHJvdl91c2VyaWQiOiAiMzQ3OThhNzUtZmE0ZC00ZWU0LWEzOTktZmVkNTM2MzNhZDRlIiwgImp0aSI6ICI4YmQ4Zjg2ZC1jZjlkLTQ5NjQtODliMS02M2YzNDZkMWMxMzciLCAiX2FjcyI6ICJhY2NvdW50cyIgfQ.Od6i2v_siXljmIYnM0L_QFgOcwfP_PEs8UgS7T0XU43HrF01HCw_HFvrlKhdpttGPLnF02o8Ok7LZ8-lbSBYyiB9J5R5-DY_2HEbKtHLok5v57jM2ChBb1-a8bMGAhGp3NOOE0rmczfU_jv-1eASp3ndqjkBX2HJONnSrSF5oafbFowHbIszg9TquAUMyaFpBUGp412Dh7J4EGLfNDD2RcGkK8xJRyxtAektrez2zIYCJXcGT5TtTorhzejaZq-rrFmyZwMz54NUUIDbZssjnT91ZuzQXaiamd82I1Op5IbUunDUVy9gyIqoD0yNs2rjC-roRXRKXjtzWZs0c_4Msw
javaloc = /Applications/Volt Iris/jre/Contents/Home
