
     slFFocusbox=frmHome_flxMainContent,frmHome_flxSideMenu,frmHome_flxHeader,frmHome_flxHoverToOpen,frmHome_flxOverlay,frmHome_flxContent

     defBtnFocus=frmHome_btnToggle

     seg2Focus=frmHome_segMenu,frmHome_segContent
