
spa.available=true
spa.version=10.0.5.0.v202512120852
spa.plugin.loc=/Users/bhargavisiryapreddy/Desktop/Bhargavi/WSSB/bundles/com.kony.spa
SuspendList_spatargetplatforms=desktopweb
desktopweb.available=true
desktopweb.version=10.0.5.0.v202512120852
desktopweb.plugin.loc=/Users/bhargavisiryapreddy/Desktop/Bhargavi/WSSB/bundles/com.kony.desktopweb
SuspendList_tctargetplatforms=
tc.plugin.loc=
tc.available=false
webcommons.plugin.loc=/Users/bhargavisiryapreddy/Desktop/Bhargavi/WSSB/bundles/com.kony.webcommons
webcommons.version=10.0.5.0.v202602021017
webcommons.available=true
jetty.portnum=8888
jetty.httpsportnum=8443
SuspendList_appid=SuspendList
SuspendList_locales=
SuspendList_sessionmgr=1
SuspendList_appversion=1.0.0
SuspendList_build.option=debug
SuspendList_jspbase=/WEB-INF/
SuspendList_devlanguage=js
apps.list=SuspendList
webapps.loc=/Users/bhargavisiryapreddy/Desktop/Bhargavi/WSSB/webapps
plugin.loc=/Users/bhargavisiryapreddy/Desktop/Bhargavi/WSSB/bundles/com.pat.tool.keditor
SuspendList_resfolder=/Users/bhargavisiryapreddy/Desktop/Bhargavi/WSSB/SuspendList/resources