
spa.available=true
spa.version=10.0.5.0.v202512120852
spa.plugin.loc=/Users/bhargavisiryapreddy/Desktop/Bhargavi/WSSB/bundles/com.kony.spa
SBCommon_spatargetplatforms=desktopweb
desktopweb.available=true
desktopweb.version=10.0.5.0.v202512120852
desktopweb.plugin.loc=/Users/bhargavisiryapreddy/Desktop/Bhargavi/WSSB/bundles/com.kony.desktopweb
SBCommon_tctargetplatforms=
tc.plugin.loc=
tc.available=false
webcommons.plugin.loc=/Users/bhargavisiryapreddy/Desktop/Bhargavi/WSSB/bundles/com.kony.webcommons
webcommons.version=10.0.5.0.v202602021017
webcommons.available=true
jetty.portnum=8888
jetty.httpsportnum=8443
SBCommon_appid=SBCommon
SBCommon_locales=ar,en,es,fa,fr,my,ps,ru,rw,so,sw,tg,uk
SBCommon_sessionmgr=1
SBCommon_appversion=1.0.0
SBCommon_build.option=debug
SBCommon_jspbase=/WEB-INF/
SBCommon_devlanguage=js
apps.list=SBCommon
webapps.loc=/Users/bhargavisiryapreddy/Desktop/Bhargavi/WSSB/webapps
plugin.loc=/Users/bhargavisiryapreddy/Desktop/Bhargavi/WSSB/bundles/com.pat.tool.keditor
SBCommon_resfolder=/Users/bhargavisiryapreddy/Desktop/Bhargavi/WSSB/SBCommon/resources