environment.name = VoltMX Technohub
mf.appname = ManageScheme
mf.app.version = 1.0
mf.runtime.app.version = 1.0
account.id = 100000032
cloud.environment = undefined
mobilefabric.url = https://manage.hclvoltmx.com
cloud.username = undefined
cloud.password = undefined
mode = 2
project.name = undefined
version = 1.0.0
appid = ManageScheme
publish.web = undefined
publish.service = undefined
mfa.secret.key = undefined
fabric.token = eyAidHlwIjogImp3dCIsICJhbGciOiAiUlMyNTYiIH0.eyAiX2JlYXJlcl90b2tlbiI6ICI0Y2ViMTViOTU5ZTMwMzdiNDIzOWNlMTE2ZWNjMDQwY2RlZTU3MmUxYmFkMjg1NmRjNTA2NDg4ZGJhZGYxYmNiNjE1MDE4MTllZjQ5MzhjMSIsICJfZW1haWwiOiAiYmhhcmdhdmkuc2lyeWFwcmVkZHlAaGNsLmNvbSIsICJfdmVyIjogInYyLjAiLCAiaXNzIjogImh0dHBzOi8vYWNjb3VudHMuYXV0aC5oY2x2b2x0bXgubmV0IiwgIl9zY29wZSI6ICJnIiwgIl9pc3NtZXRhIjogIi9tZXRhZGF0YS85bDR2QVhkVV9WTnR0d1JNQnBsRF9nPT0iLCAiX3Nlc3Npb25faWQiOiAiNzM0MDRlNmEtZjg2MC00Yjk0LTk0YWMtNWRlNGE1MTk2YTVmIiwgIl9wdWlkIjogNDkzMTc5MzgzOTE3NiwgIl9pZHAiOiAia29ueV9hY2NvdW50cyIsICJleHAiOiAxNzczODU1MTkyLCAiaWF0IjogMTc3Mzg1MTU5MiwgIl9zZXNzaW9uX3RpZCI6ICJhY2NvdW50cyIsICJfcHJvdl91c2VyaWQiOiAiMzQ3OThhNzUtZmE0ZC00ZWU0LWEzOTktZmVkNTM2MzNhZDRlIiwgImp0aSI6ICJmZGM3ZWRmMy04ZDI3LTQ5MjktYjY1OS1jOTdhMDE2ZGE1OWMiLCAiX2FjcyI6ICJhY2NvdW50cyIgfQ.D6FbTExZJGiLR8uiP2tocYjwC3uigkqaX7b-qb9x3EaFmus3YLr4n6sfOxF4vSTvXb5AvtYfLiweBXPRpRI5WUmxIoGgN05ffeGuHGTHpG1TO98-ob_txyGK3SwtQ5d3rWqL0kPN3As_R-ABKCGiUfBj8c6SMhzmdovmSFS6Ww9VVibiVKp--ObIG_TbkJturNWaQOesoyy8CET0UMkQ_ZtvSUuFrKY83C-MfGPGPhziOXeow2QOASPOdxXRZJek1kUvuKplm0L96u6iDcIJBdkno2ofN5DgByMiBOjCWx2pMhxeq_SQOX-iT5KnpxKNwD5QgNowut4oYnGtZfsLYg
javaloc = /Applications/Volt Iris/jre/Contents/Home
