
     sknFlxTrans=frmApprovers_SideMenu_filxHome,frmApprovers_SideMenu_flxUserDetails,frmApprovers_SideMenu,frmApprovers_FormHeader,frmApprovers_FormHeader,frmApprovers_flxEmployeeNumber,frmApprovers_flxEmailAddress,frmApprovers_flxMobileNumber

     slFFocusbox=frmApprovers_flxAddApproval

     defTextBoxFocus=frmApprovers_ApproverName_txtBox,frmApprovers_EmployeeNumber_txtBox,frmApprovers_EmailAddress_txtBox,frmApprovers_MobileNumber_txtBox

     sknFlxBGEDF5FF=frmApprovers_segHeader,frmApprovers_segHeader
