
     slFFocusbox=frmApprovers_flxAddApproval

     sknFlxTrans=frmApprovers_flxEmployeeNumber,frmApprovers_flxEmailAddress,frmApprovers_flxMobileNumber,frmApprovers_SideMenu_filxHome,frmApprovers_SideMenu_flxUserDetails

     sknFlxBGEDF5FF=frmApprovers_segHeader,frmApprovers_segHeader
