
     sknFlxTrans=frmAddScheme_SideMenu_filxHome,frmAddScheme_SideMenu_flxUserDetails,frmAddScheme_SideMenu,frmAddScheme_FormHeader,frmAddScheme_FormHeader,frmAddScheme_CopyFlexContainer0acb437d183354f

     slFFocusbox=frmAddScheme_flxSegMethodContainer,frmAddScheme_AddMethod,frmAddScheme_SuspendStatus,frmAddScheme_EmployementType,frmAddScheme_EmpIsActiveGovPayRoll,frmAddScheme_empSep,frmAddScheme_EmpProbationFlag,frmAddScheme_flxSchDetailsPopup,frmAddScheme_AlertUp

     segTrans=frmAddScheme_segMethodContainer,frmAddScheme_SegSuspendList_segSuspend

     defListBoxFocus=frmAddScheme_AddMethod_listData,frmAddScheme_SuspendStatus_listData,frmAddScheme_EmployementType_listData,frmAddScheme_EmpIsActiveGovPayRoll_listData,frmAddScheme_EmpProbationFlag_listData

     defTextBoxFocus=frmAddScheme_SchemeName_txtBox,frmAddScheme_SchemeNumber_txtBox,frmAddScheme_EmployerName_txtBox,frmAddScheme_CIFNumber_txtBox,frmAddScheme_RegistrationNumber_txtBox,frmAddScheme_DesignatedContName_txtBox,frmAddScheme_DesignatedContactTitle_txtBox,frmAddScheme_DesignatedCOntactPhone_txtBox,frmAddScheme_DesignatedContactEmail_txtBox,frmAddScheme_MaxLendLimit_txtBox,frmAddScheme_txtSrchScheme,frmAddScheme_EmpCIFNumber_txtBox,frmAddScheme_EmpIDNumber_txtBox,frmAddScheme_EmpCustomerName_txtBox,frmAddScheme_EmpDepartmentName_txtBox,frmAddScheme_EmpStatutoryDed_txtBox,frmAddScheme_EMPAllowance_txtBox,frmAddScheme_EmpOtherDeduction_txtBox,frmAddScheme_EmpStandbicResv_txtBox,frmAddScheme_EmpAffordability_txtBox,frmAddScheme_EmpSummaryOFIns_txtBox,frmAddScheme_EmpMaxLendLimit_txtBox

     defTextAreaFocus=frmAddScheme_txtArea

     sknFlxBGEDF5FF=frmAddScheme_segHeader,frmAddScheme_segHeader

     sknBtnGrey=frmAddScheme_AlertUp_btnCancel

     sknBtnBlue=frmAddScheme_AlertUp_btnExist,frmAddScheme_AlertUp_btnRequestHistory
