
     slFFocusbox=frmLogin_flxAuth,frmLogin_flxAccess,frmLogin_flxAvailable,frmLogin_flxUserName,frmLogin_flxPassword,frmLogin_FlexContainer0i93570251bf644

     sknTxtBxTrans=frmLogin_txtUserName,frmLogin_txtPwd
