
     sknFlxTrans=frmRemoveScheme_SideMenu_filxHome,frmRemoveScheme_SideMenu_flxUserDetails,frmRemoveScheme_flxAddMethod,frmRemoveScheme_CopyFlexContainer0acb437d183354f

     slFFocusbox=frmRemoveScheme_flxSegMethodContainer,frmRemoveScheme_AddMethod,frmRemoveScheme_SuspendStatus,frmRemoveScheme_EmployementType,frmRemoveScheme_EmpIsActiveGovPayRoll,frmRemoveScheme_empSep,frmRemoveScheme_EmpProbationFlag,frmRemoveScheme_SuspenEntryHdr,frmRemoveScheme_SuspenEntryHdr,frmRemoveScheme_flxSchDetailsPopup,frmRemoveScheme_AlertUp

     segTrans=frmRemoveScheme_segMethodContainer,frmRemoveScheme_SegSuspendList_segSuspend

     defListBoxFocus=frmRemoveScheme_AddMethod_listData,frmRemoveScheme_SuspendStatus_listData,frmRemoveScheme_EmployementType_listData,frmRemoveScheme_EmpIsActiveGovPayRoll_listData,frmRemoveScheme_EmpProbationFlag_listData

     defTextBoxFocus=frmRemoveScheme_txtEmployeeSrch,frmRemoveScheme_txtSrchScheme,frmRemoveScheme_txtSchemeSrch

     defTextAreaFocus=frmRemoveScheme_txtArea

     sknFlxBGEDF5FF=frmRemoveScheme_segHeader,frmRemoveScheme_segHeader

     sknSegRowFocus=frmRemoveScheme_SuspensionEntries_segSuspendEntry

     sknBtnGrey=frmRemoveScheme_AlertUp_btnCancel

     sknBtnBlue=frmRemoveScheme_AlertUp_btnExist,frmRemoveScheme_AlertUp_btnRequestHistory
