
     sknFlxTrans=frmRemoveScheme_SideMenu_filxHome,frmRemoveScheme_SideMenu_flxUserDetails,frmRemoveScheme_SideMenu,frmRemoveScheme_FormHeader,frmRemoveScheme_flxAddMethod,frmRemoveScheme_CopyFlexContainer0acb437d183354f

     slFFocusbox=frmRemoveScheme_flxSegMethodContainer,frmRemoveScheme_AddMethod,frmRemoveScheme_SuspendStatus,frmRemoveScheme_EmployementType,frmRemoveScheme_EmpIsActiveGovPayRoll,frmRemoveScheme_empSep,frmRemoveScheme_EmpProbationFlag,frmRemoveScheme_flxSchDetailsPopup,frmRemoveScheme_AlertUp

     segTrans=frmRemoveScheme_segMethodContainer,frmRemoveScheme_SegSuspendList_segSuspend

     defListBoxFocus=frmRemoveScheme_AddMethod_listData,frmRemoveScheme_SuspendStatus_listData,frmRemoveScheme_EmployementType_listData,frmRemoveScheme_EmpIsActiveGovPayRoll_listData,frmRemoveScheme_EmpProbationFlag_listData

     defTextBoxFocus=frmRemoveScheme_SchemeName_txtBox,frmRemoveScheme_SchemeNumber_txtBox,frmRemoveScheme_EmployerName_txtBox,frmRemoveScheme_CIFNumber_txtBox,frmRemoveScheme_RegistrationNumber_txtBox,frmRemoveScheme_DesignatedContName_txtBox,frmRemoveScheme_DesignatedContactTitle_txtBox,frmRemoveScheme_DesignatedCOntactPhone_txtBox,frmRemoveScheme_DesignatedContactEmail_txtBox,frmRemoveScheme_MaxLendLimit_txtBox,frmRemoveScheme_txtEmployeeSrch,frmRemoveScheme_txtSrchScheme,frmRemoveScheme_EmpCIFNumber_txtBox,frmRemoveScheme_EmpIDNumber_txtBox,frmRemoveScheme_EmpCustomerName_txtBox,frmRemoveScheme_EmpDepartmentName_txtBox,frmRemoveScheme_EmpStatutoryDed_txtBox,frmRemoveScheme_EMPAllowance_txtBox,frmRemoveScheme_EmpOtherDeduction_txtBox,frmRemoveScheme_EmpStandbicResv_txtBox,frmRemoveScheme_EmpAffordability_txtBox,frmRemoveScheme_EmpSummaryOFIns_txtBox,frmRemoveScheme_EmpMaxLendLimit_txtBox,frmRemoveScheme_txtSchemeSrch

     defTextAreaFocus=frmRemoveScheme_txtArea

     sknFlxBGEDF5FF=frmRemoveScheme_segHeader,frmRemoveScheme_segHeader

     sknBtnGrey=frmRemoveScheme_AlertUp_btnCancel

     sknBtnBlue=frmRemoveScheme_AlertUp_btnExist,frmRemoveScheme_AlertUp_btnRequestHistory
