
     sknFlxTrans=frmRemoveSuspend_SideMenu_filxHome,frmRemoveSuspend_SideMenu_flxUserDetails,frmRemoveSuspend_flxRight,frmRemoveSuspend_flxRemoveStatusHdr,frmRemoveSuspend_flxSeparator,frmRemoveSuspend_flxListSource,frmRemoveSuspend_flxSepLine,frmRemoveSuspend_flxTypeEntry,frmRemoveSuspend_flxSearchCriteria,frmRemoveSuspend_flxSrch,frmRemoveSuspend_flxSrchoption,frmRemoveSuspend_flxDocUpload,frmRemoveSuspend_flxUploadDoc,frmRemoveSuspend_flxReason,frmRemoveSuspend_flxReasonBox,frmRemoveSuspend_flxSuspensionHdr,frmRemoveSuspend_CopyflxSeparator0g5f39bbc2ef049,frmRemoveSuspend_flxInner,frmRemoveSuspend_flxButtons

     sknFlxSrcTrans=frmRemoveSuspend_flxSrcRemoveSuspendList

     sknFlxWhiteBGBlckBrdr=frmRemoveSuspend_flxRemoveSusList,frmRemoveSuspend_flxSuspensionEntry

     sknFlxTextBox=frmRemoveSuspend_flxSelectedSource,frmRemoveSuspend_flxSelectedType,frmRemoveSuspend_flxSelectedCriteria

     sknFlxWhite=frmRemoveSuspend_flxSegSourceContainer,frmRemoveSuspend_flxSegTypeContainer,frmRemoveSuspend_flxSegCriteriaContainer

     segTrans=frmRemoveSuspend_segNewListSource,frmRemoveSuspend_segTypeEntry,frmRemoveSuspend_segSearchCriteria

     sknTxtTransSUSMA=frmRemoveSuspend_txtSearch

     sknFlxUpload=frmRemoveSuspend_flxChooseFile

     sknBtnBlue=frmRemoveSuspend_btnImportFile,frmRemoveSuspend_btnRemoveEntry,frmRemoveSuspend_btnRemoveSubmit

     sknTxtAraGrey=frmRemoveSuspend_txtAraReason

     sknFlxWhiteBdr=frmRemoveSuspend_flxSep

     slFFocusbox=frmRemoveSuspend_SuspenEntryHdr,frmRemoveSuspend_SuspenEntryHdr

     sknSegRowFocus=frmRemoveSuspend_SuspensionEntries_segSuspendEntry

     sknBtnGrey=frmRemoveSuspend_btnRemoveExist
