
     sknFlxTrans=frmSchemeReqHistory_SideMenu_filxHome,frmSchemeReqHistory_SideMenu_flxUserDetails,frmSchemeReqHistory_SideMenu,frmSchemeReqHistory_FormHeader

     slFFocusbox=frmSchemeReqHistory_SrchTextBox,frmSchemeReqHistory_SrchTextBox

     sknFlxTextBox=frmSchemeReqHistory_SegDropDown,frmSchemeReqHistory_SegDropDown

     segTrans=frmSchemeReqHistory_SegDropDown_segDropDwn,frmSchemeReqHistory_SegSuspendList_segSuspend

     sknFlxBGEDF5FF=frmSchemeReqHistory_segHeader,frmSchemeReqHistory_segHeader
