
     sknFlxTrans=frmSchHisDetails_SideMenu,frmSchHisDetails_SideMenu_flxUserDetails,frmSchHisDetails_SideMenu,frmSchHisDetails_FormHeader,frmSchHisDetails_FormHeader

     sknFlxSrcTrans=frmSchHisDetails_SideMenu_flxSegMenu

     seg2Focus=frmSchHisDetails_SideMenu_segMenu

     sknFlxBGEDF5FF=frmSchHisDetails_segHeader,frmSchHisDetails_segHeader,frmSchHisDetails_flxSegHdr,frmSchHisDetails_flxSegHdr

     segTrans=frmSchHisDetails_SegSuspendList_segSuspend,frmSchHisDetails_segApprovalStatus_segSuspend

     slFFocusbox=frmSchHisDetails_flxTxtArea

     defTextAreaFocus=frmSchHisDetails_txtArea
