
     sknFlxTrans=frmSchemeDetails_SideMenu_filxHome,frmSchemeDetails_SideMenu_flxUserDetails

     sknFlxBGEDF5FF=frmSchemeDetails_segHeader,frmSchemeDetails_segHeader

     seg2Focus=frmSchemeDetails_segSchemeDetails

     slFFocusbox=frmSchemeDetails_SrchTextBox,frmSchemeDetails_SrchTextBox,frmSchemeDetails_SuspenEntryHdr,frmSchemeDetails_SuspenEntryHdr,frmSchemeDetails_flxPopup

     sknSegRowFocus=frmSchemeDetails_SuspensionEntries_segSuspendEntry
