
     sknFlxTrans=frmSuspendList_flxMain,frmSuspendList_flxRight,frmSuspendList_FormHeader,frmSuspendList_SideMenu_filxHome,frmSuspendList_SideMenu_flxUserDetails

     slFFocusbox=frmSuspendList_SrchTextBox,frmSuspendList_SrchTextBox

     segTrans=frmSuspendList_SegSuspendList_segSuspend
