
     sknFlxTrans=frmSusHistoryDetails_flxMain,frmSusHistoryDetails_flxRight,frmSusHistoryDetails_FormHeader,frmSusHistoryDetails_FormHeader,frmSusHistoryDetails_SegSuspendList,frmSusHistoryDetails_flxApprovalHdr,frmSusHistoryDetails_SegApprovalAction,frmSusHistoryDetails_flxSeparator,frmSusHistoryDetails_flxAddComments,frmSusHistoryDetails_flxButtons,frmSusHistoryDetails_SideMenu_filxHome,frmSusHistoryDetails_SideMenu_flxUserDetails

     sknFlxSrcTrans=frmSusHistoryDetails_flxSrcHistoryDetails

     sknFlxWhiteBdr=frmSusHistoryDetails_flxSusHisDetails,frmSusHistoryDetails_flxApprovalStatus,frmSusHistoryDetails_flxApprovalAction

     sknFlxBGEDF5FF=frmSusHistoryDetails_segHeader,frmSusHistoryDetails_HdrApprovalStatus

     slFFocusbox=frmSusHistoryDetails_segHeader,frmSusHistoryDetails_HdrApprovalStatus

     segTrans=frmSusHistoryDetails_SegSuspendList_segSuspend,frmSusHistoryDetails_SegApprovalAction_segSuspend

     sknFlxTextBox=frmSusHistoryDetails_flxTextArea

     skntxtAraTrans=frmSusHistoryDetails_txtComments
