
     sknFlxTrans=frmSchemeDetails_SideMenu_filxHome,frmSchemeDetails_SideMenu_flxUserDetails,frmSchemeDetails_SideMenu,frmSchemeDetails_FormHeader

     slFFocusbox=frmSchemeDetails_SrchTextBox,frmSchemeDetails_SrchTextBox,frmSchemeDetails_SuspenEntryHdr,frmSchemeDetails_SuspenEntryHdr,frmSchemeDetails_flxPopup

     sknSegRowFocus=frmSchemeDetails_SuspensionEntries_segSuspendEntry
