
     sknFlxTrans=frmSuspendList_flxMain,frmSuspendList_SideMenu_filxHome,frmSuspendList_SideMenu_flxUserDetails,frmSuspendList_flxRight

     slFFocusbox=frmSuspendList_SrchTextBox,frmSuspendList_SrchTextBox

     segTrans=frmSuspendList_SegSuspendList_segSuspend
