
     sknFlxTrans=frmSchHisDetails_SideMenu_filxHome,frmSchHisDetails_SideMenu_flxUserDetails

     sknFlxBGEDF5FF=frmSchHisDetails_segHeader,frmSchHisDetails_segHeader,frmSchHisDetails_flxSegHdr,frmSchHisDetails_flxSegHdr

     segTrans=frmSchHisDetails_SegSuspendList_segSuspend,frmSchHisDetails_segApprovalStatus_segSuspend

     slFFocusbox=frmSchHisDetails_flxTxtArea

     defTextAreaFocus=frmSchHisDetails_txtArea
