
     sknFlxTrans=frmSBHome_SideMenu,frmSBHome_SideMenu_flxUserDetails,frmSBHome_SideMenu,frmSBHome_FormHeader,frmSBHome_FormHeader

     sknFlxSrcTrans=frmSBHome_SideMenu_flxSegMenu

     seg2Focus=frmSBHome_SideMenu_segMenu
