
     slFFocusbox=Form1_FlexContainer0gfb0e5faacd949,Form1_RiskRateChart,Form1_RiskRateChart_flxPin,Form1_RiskRateChart_flxMainValueSubmit,Form1_RiskRateChart

     defTextBoxFocus=Form1_RiskRateChart_txtRating

     defBtnFocus=Form1_RiskRateChart_btnSubmit
