
     sknFlxTrans=frmSchemeReqHistory_SideMenu,frmSchemeReqHistory_SideMenu_flxUserDetails,frmSchemeReqHistory_SideMenu,frmSchemeReqHistory_FormHeader,frmSchemeReqHistory_FormHeader

     sknFlxSrcTrans=frmSchemeReqHistory_SideMenu_flxSegMenu

     seg2Focus=frmSchemeReqHistory_SideMenu_segMenu

     slFFocusbox=frmSchemeReqHistory_SrchTextBox,frmSchemeReqHistory_SrchTextBox

     sknFlxTextBox=frmSchemeReqHistory_SegDropDown,frmSchemeReqHistory_SegDropDown

     segTrans=frmSchemeReqHistory_SegDropDown_segDropDwn,frmSchemeReqHistory_SegSuspendList_segSuspend

     sknFlxBGEDF5FF=frmSchemeReqHistory_segHeader,frmSchemeReqHistory_segHeader
