
     sknFlxTrans=frmSchemeDetails_SideMenu,frmSchemeDetails_SideMenu_flxUserDetails,frmSchemeDetails_SideMenu,frmSchemeDetails_FormHeader,frmSchemeDetails_FormHeader

     sknFlxSrcTrans=frmSchemeDetails_SideMenu_flxSegMenu

     seg2Focus=frmSchemeDetails_SideMenu_segMenu

     slFFocusbox=frmSchemeDetails_SrchTextBox,frmSchemeDetails_SrchTextBox,frmSchemeDetails_SuspenEntryHdr,frmSchemeDetails_SuspenEntryHdr,frmSchemeDetails_flxPopup

     sknSegRowFocus=frmSchemeDetails_SuspensionEntries_segSuspendEntry
