
     sknFlxTrans=frmSchemeApprover_SideMenu_filxHome,frmSchemeApprover_SideMenu_flxUserDetails

     sknFlxBGEDF5FF=frmSchemeApprover_segHeader,frmSchemeApprover_segHeader

     slFFocusbox=frmSchemeApprover_flxAlert,frmSchemeApprover_AlertUp

     sknBtnGrey=frmSchemeApprover_AlertUp_btnCancel

     sknBtnBlue=frmSchemeApprover_AlertUp_btnExist,frmSchemeApprover_AlertUp_btnRequestHistory
