
     slFFocusbox=frmSchemeApprover_flxLeft,frmSchemeApprover_flxAddEdit,frmSchemeApprover_flxAlert,frmSchemeApprover_AlertUp

     sknFlxTrans=frmSchemeApprover_SideMenu,frmSchemeApprover_SideMenu_flxUserDetails,frmSchemeApprover_SideMenu,frmSchemeApprover_FormHeader,frmSchemeApprover_FormHeader

     sknFlxSrcTrans=frmSchemeApprover_SideMenu_flxSegMenu

     seg2Focus=frmSchemeApprover_SideMenu_segMenu

     defTextBoxFocus=frmSchemeApprover_ApproverName_txtBox,frmSchemeApprover_EmployeeNumber_txtBox,frmSchemeApprover_EmailAddress_txtBox,frmSchemeApprover_MobileNumber_txtBox

     defBtnFocus=frmSchemeApprover_btnAddEditAppr

     sknFlxBGEDF5FF=frmSchemeApprover_segHeader,frmSchemeApprover_segHeader

     sknBtnGrey=frmSchemeApprover_AlertUp_btnCancel

     sknBtnBlue=frmSchemeApprover_AlertUp_btnExist,frmSchemeApprover_AlertUp_btnRequestHistory
