{
    "defBtnBlockedUI": {
        "background_color": "E6E6E600",
        "bg_type": "one",
        "border_color": "ffffff00",
        "border_radius": 100,
        "border_style": "custom",
        "border_type": 0,
        "border_width": 1,
        "font_color": "8F8F8F00",
        "font_name": "Helvetica",
        "font_size": 150,
        "font_style": "normal",
        "font_weight": "500",
        "wType": "Button"
    },
    "defBtnFocus": {
        "background_color": "7E909E00",
        "bg_type": "one",
        "border_color": "ffffff00",
        "border_radius": 100,
        "border_style": "custom",
        "border_type": 0,
        "border_width": 1,
        "font_color": "ffffff00",
        "font_name": "Helvetica",
        "font_size": 150,
        "font_style": "normal",
        "font_weight": "500",
        "wType": "Button"
    },
    "defBtnHover": {
        "background_color": "3d546600",
        "bg_type": "one",
        "border_color": "ffffff00",
        "border_radius": 100,
        "border_style": "custom",
        "border_type": 0,
        "border_width": 1,
        "font_color": "ffffff00",
        "font_name": "Helvetica",
        "font_size": 150,
        "font_style": "normal",
        "font_weight": "500",
        "wType": "Button"
    },
    "defBtnNormal": {
        "background_color": "58738700",
        "bg_type": "one",
        "border_color": "ffffff00",
        "border_radius": 100,
        "border_style": "custom",
        "border_type": 0,
        "border_width": 1,
        "font_color": "ffffff00",
        "font_name": "Helvetica",
        "font_size": 150,
        "font_style": "normal",
        "font_weight": "500",
        "wType": "Button"
    },
    "defBtnPressed": {
        "background_color": "35495800",
        "bg_type": "one",
        "border_color": "ffffff00",
        "border_radius": 100,
        "border_style": "custom",
        "border_type": 0,
        "border_width": 1,
        "font_color": "ffffff00",
        "font_name": "Helvetica",
        "font_size": 150,
        "font_style": "normal",
        "font_weight": "500",
        "wType": "Button"
    },
    "defLabel": {
        "background_color": "00000064",
        "bg_type": "one",
        "border_color": "14A1DE00",
        "border_style": "plain",
        "border_type": 0,
        "border_width": 1,
        "font_color": "21212100",
        "font_name": "Helvetica",
        "font_size": 200,
        "font_style": "normal",
        "font_weight": "400",
        "wType": "Label"
    },
    "defTextAreaBlockedUI": {
        "background_color": "F3F3F300",
        "bg_type": "one",
        "border_color": "ADADAD00",
        "border_style": "plain",
        "border_type": 0,
        "border_width": 1,
        "font_color": "33333300",
        "font_name": "Helvetica",
        "font_size": 107,
        "font_style": "normal",
        "font_weight": "400",
        "wType": "TextArea"
    },
    "defTextAreaHover": {
        "background_color": "ffffff00",
        "bg_type": "one",
        "border_color": "14a1de00",
        "border_style": "plain",
        "border_type": 0,
        "border_width": 1,
        "font_color": "33333300",
        "font_name": "Helvetica",
        "font_size": 107,
        "font_style": "normal",
        "font_weight": "400",
        "wType": "TextArea"
    },
    "defTextBoxBlockedUI": {
        "background_color": "f3f3f300",
        "bg_type": "one",
        "border_color": "66666600",
        "border_radius": 2,
        "border_style": "custom",
        "border_type": 0,
        "border_width": 1,
        "font_color": "00000028",
        "font_name": "Helvetica",
        "font_size": 107,
        "font_style": "italic",
        "font_weight": "400",
        "wType": "TextField"
    },
    "sknLblDescription": {
        "background_color": "00000064",
        "bg_type": "one",
        "border_color": "42424200",
        "border_style": "plain",
        "border_type": 0,
        "border_width": 0,
        "font_color": "57575700",
        "font_name": "Helvetica",
        "font_size": 92,
        "font_style": "normal",
        "font_weight": "normal",
        "forked": false,
        "wType": "Label"
    },
    "sknLblRowHeading": {
        "background_color": "00000064",
        "bg_type": "one",
        "border_type": 0,
        "font_color": "00000000",
        "font_name": "Helvetica",
        "font_size": 107,
        "font_style": "normal",
        "font_weight": "bold",
        "forked": true,
        "shadow": {
            "br": 0,
            "color": "00000000",
            "inner": false,
            "nm": 0,
            "x": 0,
            "y": 0
        },
        "text_shadow": {
            "br": 0,
            "color": "00000000",
            "nm": 0,
            "x": 0,
            "y": 0
        },
        "wType": "Label"
    },
    "sknLblStrip": {
        "background_color": "4b88f100",
        "bg_type": "one",
        "border_color": "42424200",
        "border_style": "plain",
        "border_type": 0,
        "border_width": 0,
        "font_color": "4b88f100",
        "font_name": "Helvetica",
        "font_size": 70,
        "font_style": "normal",
        "font_weight": "normal",
        "forked": false,
        "wType": "Label"
    },
    "sknLblTimeStamp": {
        "background_color": "00000064",
        "bg_type": "one",
        "border_color": "42424200",
        "border_style": "plain",
        "border_type": 0,
        "border_width": 0,
        "font_color": "8e8e8e00",
        "font_name": "Helvetica",
        "font_size": 92,
        "font_style": "normal",
        "font_weight": "normal",
        "forked": false,
        "wType": "Label"
    },
    "sknSampleRowTemplate": {
        "background_color": "82485d00",
        "bg_type": "one",
        "border_color": "00000000",
        "border_style": "plain",
        "border_type": 0,
        "border_width": 0,
        "wType": "FlexContainer"
    },
    "sknSampleSectionHeaderTemplate": {
        "background_color": "ffffff00",
        "bg_type": "one",
        "border_color": "00000000",
        "border_style": "plain",
        "border_type": 0,
        "border_width": 0,
        "wType": "FlexContainer"
    },
    "sknSectionHeaderLabelSkin": {
        "background_color": "94019464",
        "bg_type": "one",
        "border_type": 0,
        "font_color": "00000000",
        "font_name": "Helvetica",
        "font_size": 125,
        "font_style": "normal",
        "font_weight": "bold",
        "forked": true,
        "shadow": {
            "br": 0,
            "color": "00000000",
            "inner": false,
            "nm": 0,
            "x": 0,
            "y": 0
        },
        "text_shadow": {
            "br": 0,
            "color": "00000000",
            "nm": 0,
            "x": 0,
            "y": 0
        },
        "wType": "Label"
    },
    "slCameraFocus": {
        "background_image": "camera_focus.png",
        "background_image_dimensions": {
            "common": {
                "height": 43,
                "width": 43
            }
        },
        "bg_type": "image",
        "border_color": "00000000",
        "border_style": "plain",
        "border_type": 0,
        "border_width": 0,
        "font_color": "00000000",
        "font_name": "Helvetica",
        "font_size": 100,
        "font_style": "normal",
        "font_weight": "400",
        "wType": "Camera"
    },
    "slDynamicNotificationForm": {
        "background_color": "00000000",
        "bg_type": "one",
        "border_color": "ffffff00",
        "wType": "WatchDynamicNotificationForm"
    },
    "slFBlockedUIbox": {
        "background_color": "f3f3f300",
        "bg_type": "one",
        "border_color": "ADADAD00",
        "border_style": "custom",
        "border_type": 0,
        "border_width": 1,
        "font_name": "Helvetica",
        "wType": "FlexContainer"
    },
    "slFFocusbox": {
        "background_color": "00000064",
        "bg_type": "one",
        "border_color": "14a1de00",
        "border_style": "custom",
        "border_type": 0,
        "border_width": 1,
        "font_name": "Helvetica",
        "wType": "FlexContainer"
    },
    "slFSBlockedUIbox": {
        "background_color": "f3f3f300",
        "bg_type": "one",
        "border_color": "ADADAD00",
        "border_style": "custom",
        "border_type": 0,
        "border_width": 1,
        "font_name": "Helvetica",
        "wType": "FlexScrollContainer"
    },
    "slFSFocusSbox": {
        "background_color": "00000064",
        "bg_type": "one",
        "border_color": "14a1de00",
        "border_style": "custom",
        "border_type": 0,
        "border_width": 1,
        "wType": "FlexScrollContainer"
    },
    "slFbox": {
        "background_color": "00000064",
        "bg_type": "one",
        "border_color": "66666600",
        "border_style": "custom",
        "border_type": 0,
        "border_width": 1,
        "font_name": "Helvetica",
        "wType": "FlexContainer"
    },
    "slForm": {
        "background_color": "ffffff00",
        "bg_type": "one",
        "border_color": "ffffff00",
        "wType": "Form"
    },
    "slSplashiOS": {
        "background_color": "00000000",
        "bg_type": "one",
        "border_color": "00000000",
        "wType": "Form"
    },
    "slStaticNotificationForm": {
        "background_color": "00000000",
        "bg_type": "one",
        "wType": "WatchStaticNotificationForm"
    },
    "slTitleBar": {
        "background_color": "ffffff00",
        "bg_type": "one",
        "font_color": "33333300",
        "font_name": "System",
        "font_size": 100,
        "font_weight": "normal",
        "wType": "TitleBar"
    },
    "slWatchForm": {
        "background_color": "00000000",
        "bg_type": "one",
        "wType": "Form"
    },
    "theme_styles": {}
}