environment.name = VoltMX Technohub
mf.appname = Customer360
mf.app.version = 1.0
mf.runtime.app.version = 1.0
account.id = 100000032
cloud.environment = undefined
mobilefabric.url = https://manage.hclvoltmx.com
cloud.username = undefined
cloud.password = undefined
mode = 2
project.name = undefined
version = 1.0.0
appid = Customer360
publish.web = undefined
publish.service = undefined
mfa.secret.key = undefined
fabric.token = eyAidHlwIjogImp3dCIsICJhbGciOiAiUlMyNTYiIH0.eyAiX2JlYXJlcl90b2tlbiI6ICI3ZTBjMTUzMTIzYzUwMzg1OTBiNzQ5ZDAwNmI2MDJjYTA4Y2ZhMmQ1NWYzMzkxYmYxY2YwYTI0NWZkMDQ4MzljYTYwMGU5YTYxOWJlOTJmOCIsICJfZW1haWwiOiAiYmhhcmdhdmkuc2lyeWFwcmVkZHlAaGNsLmNvbSIsICJfdmVyIjogInYyLjAiLCAiaXNzIjogImh0dHBzOi8vYWNjb3VudHMuYXV0aC5oY2x2b2x0bXgubmV0IiwgIl9zY29wZSI6ICJnIiwgIl9pc3NtZXRhIjogIi9tZXRhZGF0YS85bDR2QVhkVV9WTnR0d1JNQnBsRF9nPT0iLCAiX3Nlc3Npb25faWQiOiAiNjcwYjRhMGYtMzQzZi00MDA2LThiYWYtNDMzYWVmZjI1YzBlIiwgIl9wdWlkIjogNDkzMTc5MzgzOTE3NiwgIl9pZHAiOiAia29ueV9hY2NvdW50cyIsICJleHAiOiAxNzgxMjQ3MTkxLCAiaWF0IjogMTc4MTI0MzU5MSwgIl9zZXNzaW9uX3RpZCI6ICJhY2NvdW50cyIsICJfcHJvdl91c2VyaWQiOiAiMzQ3OThhNzUtZmE0ZC00ZWU0LWEzOTktZmVkNTM2MzNhZDRlIiwgImp0aSI6ICJiMzhjMzdmMy1kOTNhLTQwMDQtOTk4NC0xOTQ4N2YxMWNmOGYiLCAiX2FjcyI6ICJhY2NvdW50cyIgfQ.KPDLim0XmjKTJgHCLU6GdMRCiO6CaboiXrCKluJwDpB8n-MwVYhqsUKqorcWbJZQAkDTd2nfj2dRxyghjhPWmgfvl8gfBkKqGUdjfnRexuBFNZ0yR6VOC6R0D93DMVnREprsE07Ey9wa_BuuhWunRpiQa3-UY7nJ8ArxZTe8Jy5MBsuxdp895PfAwaWXPoFhGm5lfbBJUflSaOEtBPjK8wUyKZvT5laIzezFHqcu92Y1nTaCoURoiupAlKazQ7GqA8EK8SqWYoDksUy5xFIdtUKrSdvB6F2_6ZdUxEE03GG-9yMcb23_sO8koLe0vVf1pEEi_FtLVfIAjeuWM_W1GQ
javaloc = /Applications/Volt Iris/jre/Contents/Home
