
spa.available=true
spa.version=10.0.5.0.v202512120852
spa.plugin.loc=/Users/bhargavisiryapreddy/Desktop/Bhargavi/WSSB/bundles/com.kony.spa
Customer360_spatargetplatforms=desktopweb
desktopweb.available=true
desktopweb.version=10.0.5.0.v202512120852
desktopweb.plugin.loc=/Users/bhargavisiryapreddy/Desktop/Bhargavi/WSSB/bundles/com.kony.desktopweb
Customer360_tctargetplatforms=
tc.plugin.loc=
tc.available=false
webcommons.plugin.loc=/Users/bhargavisiryapreddy/Desktop/Bhargavi/WSSB/bundles/com.kony.webcommons
webcommons.version=10.0.5.0.v202602021017
webcommons.available=true
jetty.portnum=8888
jetty.httpsportnum=8443
Customer360_appid=Customer360
Customer360_locales=
Customer360_sessionmgr=1
Customer360_appversion=1.0.0
Customer360_build.option=debug
Customer360_jspbase=/WEB-INF/
Customer360_devlanguage=js
apps.list=Customer360
webapps.loc=/Users/bhargavisiryapreddy/Desktop/Bhargavi/WSSB/webapps
plugin.loc=/Users/bhargavisiryapreddy/Desktop/Bhargavi/WSSB/bundles/com.pat.tool.keditor
Customer360_resfolder=/Users/bhargavisiryapreddy/Desktop/Bhargavi/WSSB/Customer360/resources