
     sknFlxTrans=frmAddSuspend_SideMenu,frmAddSuspend_SideMenu_flxUserDetails,frmAddSuspend_SideMenu,frmAddSuspend_FormHeader,frmAddSuspend_FormHeader

     slFFocusbox=frmAddSuspend_SideMenu_flxSideMenu

     sknFlxSrcTrans=frmAddSuspend_SideMenu_flxSegMenu

     seg2Focus=frmAddSuspend_SideMenu_segMenu

     defListBoxFocus=frmAddSuspend_ListSource_listData,frmAddSuspend_ListEntry_listData,frmAddSuspend_SrchCriteria_listData

     defBtnFocus=frmAddSuspend_Button0j0c9290b34aa4e

     defTextAreaFocus=frmAddSuspend_txtAra

     sknFlxBGEDF5FF=frmAddSuspend_segHeader,frmAddSuspend_segHeader

     sknBtnGrey=frmAddSuspend_AlertUp_btnCancel

     sknBtnBlue=frmAddSuspend_AlertUp_btnExist,frmAddSuspend_AlertUp_btnRequestHistory
