
     sknFlxTrans=frmHome_flxMain,frmHome_SideMenu,frmHome_SideMenu_flxUserDetails,frmHome_SideMenu,frmHome_flxRight,frmHome_FormHeader,frmHome_FormHeader

     sknFlxWhiteBdr=frmHome_flxLeft

     sknFlxSrcTrans=frmHome_SideMenu_flxSegMenu

     seg2Focus=frmHome_SideMenu_segMenu
