
     sknFlxTrans=frmRequestHistory_SideMenu,frmRequestHistory_SideMenu_flxUserDetails,frmRequestHistory_SideMenu,frmRequestHistory_FormHeader,frmRequestHistory_FormHeader

     slFFocusbox=frmRequestHistory_SideMenu_flxSideMenu,frmRequestHistory_SrchTextBox,frmRequestHistory_SrchTextBox,frmRequestHistory_flxDropDwn

     sknFlxSrcTrans=frmRequestHistory_SideMenu_flxSegMenu

     seg2Focus=frmRequestHistory_SideMenu_segMenu

     sknFlxBGEDF5FF=frmRequestHistory_segHeader,frmRequestHistory_segHeader

     segTrans=frmRequestHistory_SegSuspendList_segSuspend
