
     sknFlxTrans=frmSusHistoryDetails_flxMain,frmSusHistoryDetails_SideMenu,frmSusHistoryDetails_SideMenu_flxUserDetails,frmSusHistoryDetails_SideMenu,frmSusHistoryDetails_flxRight,frmSusHistoryDetails_FormHeader,frmSusHistoryDetails_FormHeader,frmSusHistoryDetails_SegSuspendList,frmSusHistoryDetails_flxApprovalHdr,frmSusHistoryDetails_SegApprovalAction,frmSusHistoryDetails_flxSeparator,frmSusHistoryDetails_flxAddComments,frmSusHistoryDetails_flxButtons

     slFFocusbox=frmSusHistoryDetails_SideMenu_flxSideMenu,frmSusHistoryDetails_segHeader,frmSusHistoryDetails_HdrApprovalStatus

     sknFlxSrcTrans=frmSusHistoryDetails_SideMenu_flxSegMenu,frmSusHistoryDetails_flxSrcHistoryDetails

     seg2Focus=frmSusHistoryDetails_SideMenu_segMenu

     sknFlxWhiteBdr=frmSusHistoryDetails_flxSusHisDetails,frmSusHistoryDetails_flxApprovalStatus,frmSusHistoryDetails_flxApprovalAction

     sknFlxBGEDF5FF=frmSusHistoryDetails_segHeader,frmSusHistoryDetails_HdrApprovalStatus

     segTrans=frmSusHistoryDetails_SegSuspendList_segSuspend,frmSusHistoryDetails_SegApprovalAction_segSuspend

     sknFlxTextBox=frmSusHistoryDetails_flxTextArea

     skntxtAraTrans=frmSusHistoryDetails_txtComments
