
     sknFlxTrans=frmSuspendList_flxMain,frmSuspendList_SideMenu,frmSuspendList_SideMenu_flxUserDetails,frmSuspendList_SideMenu,frmSuspendList_flxRight,frmSuspendList_FormHeader,frmSuspendList_FormHeader

     sknFlxWhiteBdr=frmSuspendList_flxLeft

     slFFocusbox=frmSuspendList_SideMenu_flxSideMenu,frmSuspendList_SrchTextBox,frmSuspendList_SrchTextBox

     sknFlxSrcTrans=frmSuspendList_SideMenu_flxSegMenu

     seg2Focus=frmSuspendList_SideMenu_segMenu

     segTrans=frmSuspendList_SegSuspendList_segSuspend
