
spa.available=true
spa.version=10.0.5.0.v202512120852
spa.plugin.loc=/Users/bhargavisiryapreddy/Desktop/Bhargavi/WSSB/bundles/com.kony.spa
StandardBank_spatargetplatforms=desktopweb
desktopweb.available=true
desktopweb.version=10.0.5.0.v202512120852
desktopweb.plugin.loc=/Users/bhargavisiryapreddy/Desktop/Bhargavi/WSSB/bundles/com.kony.desktopweb
StandardBank_tctargetplatforms=
tc.plugin.loc=
tc.available=false
webcommons.plugin.loc=/Users/bhargavisiryapreddy/Desktop/Bhargavi/WSSB/bundles/com.kony.webcommons
webcommons.version=10.0.5.0.v202602021017
webcommons.available=true
jetty.portnum=8888
jetty.httpsportnum=8443
StandardBank_appid=StandardBank
StandardBank_locales=ar,en,en_US,es
StandardBank_sessionmgr=1
StandardBank_appversion=1.0.0
StandardBank_build.option=debug
StandardBank_jspbase=/WEB-INF/
StandardBank_devlanguage=js
apps.list=StandardBank
webapps.loc=/Users/bhargavisiryapreddy/Desktop/Bhargavi/WSSB/webapps
plugin.loc=/Users/bhargavisiryapreddy/Desktop/Bhargavi/WSSB/bundles/com.pat.tool.keditor
StandardBank_resfolder=/Users/bhargavisiryapreddy/Desktop/Bhargavi/WSSB/StandardBank/resources